---
# PG volumes: 2 Longhorn replicas (survives 1 node loss)
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-postgres
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Retain
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "2"
  staleReplicaTimeout: "30"
  fromBackup: ""
  fsType: "ext4"
  dataLocality: "best-effort"
  unmapMarkSnapChainRemoved: "ignored"
---
# General replicated storage for non-PG workloads
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-replicated
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "2"
  staleReplicaTimeout: "30"
  fsType: "ext4"
  dataLocality: "best-effort"
